### ISSUE TITLE
Account for Advantage

### ISSUE THREAD

**Issue by v6** [rjb25/5e-dm-assistant#2]
Command?action 0 Bite 3.1,2.-1    
oneechan makes awkward-sounding noises at you, enter the 'exit' command to exit.
Traceback (most recent call last):
  File "basic.py", line 208, in <module>
    callAction(sender, actionKey, targetInfo.split("."))
  File "basic.py", line 194, in callAction
    applyAction(actions,targetInfo,actionKey)
  File "basic.py", line 133, in applyAction
    actions = senderJson.get("actions")
AttributeError: 'list' object has no attribute 'get'
index name hp/max_hp
0 sahuagin 14/14
1 sahuagin 14/14
2 rat 1/1
3 giant-rat -10/8
Command?

![image](https://user-images.githubusercontent.com/5750764/117752117-15f83e80-b1cb-11eb-9f69-a2b06cd3858f.png)

**Comment by v6** [comment]
"Also, we're here from The Python Foundation. 

May we come in? We won't take much of your time, we're just here to share something with you. Something important that you should know.

Alright thanks. Oh, yes, tea would be nice.

Did you know that 'list' object has no attribute 'get'? 

Well, it doesn't. And not enough people know that 'list' object has no attribute 'get'.

So we're spreading the good word. Once everyone knows that 'list' object has no attribute 'get', we'll spread it again, just to be sure. To the four corners of the earth shall we spread this important knowledge. 

It bears repeating. 'list' object has no attribute 'get'

And with that, we will 'get' ourselves out of here.

No, there's no need for that sort of thing. Just put the bat down, let's talk abou-"

**Comment by rjb25** [comment]
These were different times. Things have changed.
